# Generated by Django 2.2.18 on 2021-02-12 11:42

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField()),
                (
                    "station_id",
                    models.CharField(
                        max_length=4,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
                ("observation_time", models.DateTimeField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0.0, 0.0),
                        geography=True,
                        srid=4326,
                    ),
                ),
                (
                    "temp_c",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(-100.0),
                            django.core.validators.MaxValueValidator(70.0),
                        ],
                    ),
                ),
                (
                    "dewpoint_c",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(-100.0),
                            django.core.validators.MaxValueValidator(70.0),
                        ],
                    ),
                ),
                (
                    "wind_speed_kt",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "wind_dir_degrees",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ],
                    ),
                ),
                (
                    "wind_gust_kt",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
            ],
            options={"unique_together": {("observation_time", "station_id")},},
        ),
        migrations.CreateModel(
            name="SkyCondition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sky_cover", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cloud_base_ft_agl",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(330000),
                        ],
                    ),
                ),
                (
                    "metar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sky_conditions",
                        to="metars.Metar",
                    ),
                ),
            ],
        ),
    ]
